#ifndef SERVERMANAGER_GLOBAL_H
#define SERVERMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERMANAGER_LIBRARY)
#  define SERVERMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERMANAGER_GLOBAL_H
