#ifndef OVERLAYMANAGER_GLOBAL_H
#define OVERLAYMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OVERLAYMANAGER_LIBRARY)
#  define OVERLAYMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OVERLAYMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OVERLAYMANAGER_GLOBAL_H
